### ISSUE TITLE
Custom url issue

### ISSUE THREAD

**Issue by iurii-polishchuk** [dhoer/chef-nexus3#2]
It looks like custom url breaks the cookbook:

```
nexus3[nexus] action install

           ================================================================================
           Error executing action `install` on resource 'nexus3[nexus]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `rindex' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:30:in `filename'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:40:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:38:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/tc-nexus-v3/recipes/_nexus3.rb

             1: nexus3 'nexus'

```

**Comment by dhoer** [comment]
Can you please provide an example of the url?

**Comment by dhoer** [comment]
See if 0.2.1 release fixes the issue.

**Comment by iurii-polishchuk** [comment]
Works like a charm. Thanks!
